import React, { useEffect, useState } from 'react';
import PropTypes from 'prop-types';
import { NavLink } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { getAnimes } from '../redux/Companies/Companies';
import { getDetails } from '../redux/details/details';
import { getCategorie } from '../redux/Categories/Categories';
import Loading from './loadingS';

import '../css/Menu.css';

let init = 0;

const Menu = () => {
  const [loading, setLoading] = useState(true);
  // Accessing anime data from the Redux store
  const data = useSelector((state) => state.animes);
  // Used to dispatch actions to the Redux store
  const dispatch = useDispatch();

  useEffect(() => {
    // Stop loading when there are at least 9 anime entries
    if (data.length >= 9) {
      setLoading(false);
    }

    // Fetch initial anime details and list if not already done
    if (typeof init === 'undefined' || init === 0) {
      dispatch(getDetails(1));
      setTimeout(() => { dispatch(getAnimes()); }, 500);
      init = 2;
    }

    // Fallback to set loading to false after 5 seconds, in case the data check doesn't turn it off
    const timer = loading ? setTimeout(() => setLoading(false), 5000) : null;

    // Clear the timeout if the component unmounts or if any dependencies change
    return () => clearTimeout(timer);
  }, [dispatch, loading, data]);

  // Function to dispatch a category selection action
  const sendCategorie = async (cat) => {
    dispatch(getCategorie(cat));
  };

  // Component for rendering category buttons
  const CategoryButton = ({ category, onClick }) => (
    <button
      type="button"
      className={`genre ${category.replace(/\s+/g, '')}`} // Class name generated by removing spaces from category names
      onClick={() => onClick(category)}
    >
      {category}
    </button>
  );

  // Prop types definition for CategoryButton
  CategoryButton.propTypes = {
    category: PropTypes.string.isRequired,
    onClick: PropTypes.func.isRequired,
  };

  // Array of category names
  const categories = ['Action', 'Comedy', 'Fantasy', 'Gourmet', 'Drama', 'Slice of Life'];

  return (
    <div className="categories">
      <h2>Categories</h2>
      <NavLink to="Categories">
        {/* Map over categories array to render a button for each category */}
        {categories.map((category) => (
          <CategoryButton key={category} category={category} onClick={sendCategorie} />
        ))}
      </NavLink>
      {/* Show loading component if data is still loading; otherwise, show a line break */}
      {loading ? <Loading /> : <br />}
    </div>
  );
};

export default Menu;
